name = "xboard-edge"
main = "src/index.ts"
compatibility_date = "2026-06-26"
account_id = "CLOUDFLARE_ACCOUNT_ID"

[[d1_databases]]
binding = "XBOARD_DB"
database_name = "xboard-db"
database_id = "D1_DATABASE_ID"

[[kv_namespaces]]
binding = "XBOARD_KV"
id = "KV_NAMESPACE_ID"

[assets]
directory = "./public"
binding = "ASSETS"
