name = "xboard-cron"
main = "src/index.ts"
compatibility_date = "2026-06-26"

[[d1_databases]]
binding = "XBOARD_DB"
database_name = "xboard-db"
database_id = "D1_DATABASE_ID"

[[kv_namespaces]]
binding = "XBOARD_KV"
id = "KV_NAMESPACE_ID"

[[queues.producers]]
binding = "MAIL_EVENTS"
queue = "mail-events"

[triggers]
crons = ["* * * * *", "10 0 * * *"]

