name = "xboard-analytics"
main = "src/index.ts"
compatibility_date = "2026-06-26"
account_id = "CLOUDFLARE_ACCOUNT_ID"
workers_dev = false

[cache]
enabled = true

[vars]
CLOUDFLARE_ACCOUNT_ID = "CLOUDFLARE_ACCOUNT_ID"
